apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnerreport-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnerreport-backend
  template:
    metadata:
      labels:
        app: learnerreport-backend
    spec:
      containers:
        - name: backend
          image: glenveigas4/learnerreport-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: ATLAS_URI
              value: "mongodb://mongodb-service:27017/learner_reportDB"
            - name: HASH_KEY
              value: "thisIsMyHashKey"
            - name: JWT_SECRET_KEY
              value: "thisIsMyJwtSecretKey"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: learnerreport-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
