apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnerreport-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnerreport-frontend
  template:
    metadata:
      labels:
        app: learnerreport-frontend
    spec:
      containers:
        - name: frontend
          image: glenveigas4/learnerreport-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://backend-service:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: learnerreport-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
